spring:
  datasource:
    url: jdbc:h2:mem:test
  liquibase:
    change-log: classpath:db/changelog/changes_0001.yaml
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true